services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "4173:80"
    depends_on:
      - api

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile    
    command: "/app/scripts/wait-for-it.sh -t 10 db:3306 -- npm run start"
    environment:
      MYSQL_URI: mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_USER}
      CORS_WHITELIST: ${CORS_WHITELIST}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: maraidb:11.5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_USER}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer:latest
    depends_on:
      - db